### ISSUE TITLE
添加权限的容错机制不是很好

### ISSUE THREAD

**Issue by coralh** [big-pang/laravel5.3-admin#7]
添加权限的时候, 在规则中, 如果输入了错误的路由, 后台会全部报错, 解决方法是 删掉数据库对应的权限记录, 然后 php artisan cache:clear

**Comment by big-pang** [comment]
哥, 你的是后台, 另外你可以丢一个 404到 error里

在 2016-12-20 17:19:26，"Shawn" <notifications@github.com> 写道：


添加权限的时候, 在规则中, 如果输入了错误的路由, 后台会全部报错, 解决方法是 删掉数据库对应的权限记录, 然后 php artisan cache:clear

**Comment by big-pang** [comment]
我只是写一个架子,  很多东西,  可以自己舔砖加瓦




在 2016-12-20 17:19:26，"Shawn" <notifications@github.com> 写道：


添加权限的时候, 在规则中, 如果输入了错误的路由, 后台会全部报错, 解决方法是 删掉数据库对应的权限记录, 然后 php artisan cache:clear

**Comment by coralh** [comment]
好的 ,  谢谢
